### ISSUE TITLE
Updates on benchmarks

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#58]
You published [this ](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0208073) nearly a year ago. Any updates on benchmarks?

You pointed out:

> The most likely explanation is that the former [QuTiP] uses sparse matrices during computation, whereas the latter [Quantum++] does not.

> The fundamental data types in Quantum++ are non-sparse vectors and matrices.

My questions:

Do you know by now the QuTiP outperforming Quantum++ in that test is indeed attributed to the sparse matrices?

Could you please elaborate a little more on why your design decision favors non-sparse vectors and matrices considering the apparent performance benefits of using their sparse counterparts?

Thanks.

**Comment by vsoftco** [comment]
I did not re-benchmarked the system. I decided to use dense vectors mainly because of simplicity of implementation, and also because for non-trivial (not very small/shallow) circuits, the state vector becomes relatively dense quite fast. I believe that indeed QuTiP sometime over-performs Quantum++ due to the fact that it uses sparse matrices.
