### ISSUE TITLE
Repeated measurements

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#61]
The wiki article [here ](https://en.wikipedia.org/wiki/Measurement_in_quantum_mechanics) states:

> Repeating the same measurement without any evolution of the quantum state will lead to the same result. If the preparation is repeated, subsequent measurements will likely lead to different results. 

This simple test shows the 10 measurements do often produce different results (a). 

```
    for(int i=0; i<10; i++)
    {
        std::tie(a, b, c) = measure(bell_state, gt.H, {0});
    }
```
Does that imply the experiments simulated in your Quantum++ assume the preparation is indeed repeated?

In a physical quantum computer, that would represent a scenario where the input device keeps on producing the bell state. Is that correct?

**Comment by vsoftco** [comment]
The functions in Q++ do not modify their arguments (this design was intentional, to resemble more functional-programming style and to facilitate testing). In general, in case you need to modify the argument of a function, you need to have the argument on the rhs of an assignment, like in this case where we permute the subsystems of a 3-qubit state vector |psi>

    psi =  syspermute(psi, {0,2,1}); // permutes the subsystems of psi

So if you need to simulate repeated measurements on the same state just measure the second time on the result of the previous measurement, like so:

    std::tie(m, probs, states) = measure(bell_state, gt.H, {0}); // states[m] will be our output state
    std::tie(n, probs, states) = measure(states[m], gt.H, {0}); // now n == m

**Comment by DevelopDaily** [comment]
Great. Thanks.
